### ISSUE TITLE
Ctrl+Alt+Number shortcuts broken again

### ISSUE THREAD

**Issue by gcamaril** [mikehardy/thunderlink#39] opened 2019-02-20 13:13 UTC
Hi,

the Ctrl+Alt+Number shortcuts are working fine for me when using Thunderlink 1.2.6 with ThunderBird
60.3.3 (win 32). However, when I upgrade to Thunderlink 1.2.9 the shortcuts do not work any longer.

For example, this is my entry for Ctrl+Alt+2:
`extensions.thunderlink.custom-tl-string-2;<thunderlink>`

This seems to be related to the following issue:
https://github.com/mikehardy/thunderlink/issues/36

Thanks!

**Comment by mikehardy** [comment] 2019-02-20 13:42
@gcamaril - can you put the exact entry in quotes so markdown will render it? Markdown won't take HTML unless it is in ticks like so:

`<html tag here should show up>`

Or if it is longer you do triple ticks on lines above+below:

```
this is a longer
quote block
that should show up
even <with> weird <tags>
```

**Comment by mikehardy** [comment] 2019-02-20 13:43
Actually never mind, I realized I could edit the comment and fix it - the tag was still there :-). I think we have the info we need. And some fresh markdown skills ;-)

**Comment by mikehardy** [comment] 2019-02-20 14:51
I am unable to reproduce this in Thunderbird 60.5.1 (that's win32 current I believe?) and Thunderlink 1.2.9

Can you open the console (ctrl-shift-J), hit the trashcan on the top-left (to clear output) then try a shortcut to see what happens and send the contents here? It should look something like this:


![screenshot from 2019-02-20 09-49-40](https://user-images.githubusercontent.com/782704/53100000-f5ae0d80-34f4-11e9-8b99-c40db971b874.png)

**Comment by mikehardy** [comment] 2019-02-20 14:55
As a hunch, maybe there is something going on with the preferences, since you are good with emacs, maybe you could upgrade to thunderlink 1.2.9, close thunderbird, cat the preferences through a grep -v for thunderlink and put the now thunderlink-free preferences in place, try reconfiguring with thunderlink 1.2.9 (fresh preferences) and see what happens? If that works, then maybe we have some preferences upgrade thing we need to do from 1.2.6 -&gt; 1.2.9

**Comment by gcamaril** [comment] 2019-02-20 15:21
Hi,

Using version 1.2.9, this is the console's output when I try Ctrl+Alt+1, which is defined as:
`From: <sender>`
`Subject: <subject>`
`<tbexe> <thunderlink>`

<img width="664" alt="tl1 2 9" src="https://user-images.githubusercontent.com/36072436/53101807-2d3baa80-3533-11e9-8876-b8fcfa28437b.png">

With respect to the TB version I am using, I am using TB 60.3.3 right now because using later win32 TB releases broke other parts of the addon (such as clicking on a Thunderlink from an external application). Once we resolve this one, I will update to the latest TB and see if there are still more issues ;-)

Thanks!

**Comment by gcamaril** [comment] 2019-02-20 15:38
For comparison, if I do the same as above but using version 1.2.6, everything works fine and this is the console's output:
<img width="720" alt="tl1 2 6" src="https://user-images.githubusercontent.com/36072436/53103432-4e51ca80-3536-11e9-836c-c8ba3a55af18.png">

Cheers!

**Comment by mikehardy** [comment] 2019-02-20 15:44
It's the carriage return - it needs to be '\n' now - this is as discussed here:

https://github.com/mikehardy/thunderlink/issues/36#issuecomment-457354068

I'll put a $1 on that fixing it. This does mean that we're taking working preferences from 1.2.6 and with the new control characters they aren't working in 1.2.9 anymore -  @MarioKusek the way [the replacement is done here](https://github.com/mikehardy/thunderlink/blob/master/modules/thunderlinkModule.js#L127) doesn't generate valid JSON but we send it through JSON.parse anyway ? 

You can see as an example the preference resolved in the image above - it's got newlines in it, but I'm assuming they are windows CRLFs instead of \n

**Comment by mikehardy** [comment] 2019-02-20 15:45
This may or may not actually be platform-specific but until it's reproduced on mac or linux I think it might just be windows newlines - unsure

**Comment by MarioKusek** [comment] 2019-02-20 15:46
So is your template is this?
```
From: <sender>
Subject: <subject>
<tbexe> <thunderlink>
```

**Comment by gcamaril** [comment] 2019-02-20 16:03
Using \n fixes the issue partially. That is, if I use the following with Ctrl+Alt+1, everything works fine:

`From: <sender>\nSubject: <subject>\n<tbexe> <thunderlink>\n`

Before logging this issue, I had actually tried that and it did not work. The reason seems to be that I had tried it using Ctrl+Alt+2 instead. I have now used the code above for both Ctrl+Alt+1 and Ctrl+Alt+2 and while the former one works, the latter one doesn't! When I hit Ctrl+Alt+2, there is no output at all on the console.

These are the preferences I am using:

<img width="693" alt="prefs" src="https://user-images.githubusercontent.com/36072436/53105384-b7870d00-3539-11e9-9238-a1dd5deb119d.png">

Cheers!

**Comment by MarioKusek** [comment] 2019-02-20 16:14
What is output in console when you hit Ctrl+Alt+2?

**Comment by gcamaril** [comment] 2019-02-20 16:16
The console output after hitting Ctrl+Alt+2 is absolutely nothing:
<img width="720" alt="console2" src="https://user-images.githubusercontent.com/36072436/53106395-a50dd300-353b-11e9-89ce-7a42997d10be.png">

Cheers!

**Comment by gcamaril** [comment] 2019-02-20 16:44
I have just updated to the current version of TB for win32 (60.5.1) and the issue above with Ctrl+Alt+2 is still there.

**Comment by MarioKusek** [comment] 2019-02-20 16:45
I can not reproduce it on mac :( 
On my machine it works fine.

@mikehardy Can you reproduce it on win?

**Comment by gcamaril** [comment] 2019-02-20 16:53
I have tried all the shortcuts (from 1 to 8) and the only ones that work are Ctrl+Alt+1 and Ctrl+Alt+6.

**Comment by MarioKusek** [comment] 2019-02-20 17:03
That is strange because they are declared in the same way ([look here](https://github.com/mikehardy/thunderlink/blob/master/chrome/thunderlink/content/thunderlink-overlay.xul#L18) lines 18-25).

The only thing that comes to my mind is that either some other TB plugin has the same shortcuts or the OS is using those shortcuts for something else.

Anyway, you can check active shortcuts by using plugin [Dorando keyconfig](https://addons.thunderbird.net/en-us/thunderbird/addon/dorando-keyconfig/). In the preferences of that plugin look for keys `cpCstTlStr1` where 1 is for first. There you can even change shortcut and try with new keys.

**Comment by gcamaril** [comment] 2019-02-20 17:15
Yes, I also use the keyconfig add on. It does not show anything strange either:

<img width="511" alt="keyconfig" src="https://user-images.githubusercontent.com/36072436/53110457-a04d1d00-3543-11e9-86dd-120bf6eb95ea.png">

In any case, I myself only actually use one Thunderlink shortcut, which is Ctrl+Alt+1. So, if you guys cannot reproduce the problem, feel free to close this issue.

Thanks!

**Comment by gcamaril** [comment] 2019-02-20 17:27
I have used keyconfig to define another shortcut (Shift+Q) with the same code as Ctrl+Alt+2:
`ThunderLinkChromeNS.ActivateCustomTlString(2);`

And it works. So, there must be something in my system picking the Ctrl+Alt+Number shortcuts that do not work. Being able to use keyconfig to go around that resolves all the remaining issues I had.

Thanks a lot for the quick responses!

**Comment by mikehardy** [comment] 2019-02-20 19:30
There is still the issue that previously working configs need a change manually or a migration or the regex needs a change in the extension and a new release...

**Comment by MarioKusek** [comment] 2019-02-20 20:03
Can we put in [convertEscapeCharacters](https://github.com/mikehardy/thunderlink/blob/master/modules/thunderlinkModule.js#L127) another replacement of CR to `\r` and LF to `\n` before parsing JSON?

**Comment by mikehardy** [comment] 2019-02-20 20:24
definitely - I think that would fix it up

**Closed** 2020-12-04 11:56 UTC
Labels: Platform-Specific, bug
