### ISSUE TITLE
Thunderlink Preferences broken on Ubuntu. "modules/malServices.js" not found.

### ISSUE THREAD

**Issue by chemmi** [mikehardy/thunderlink#55] opened 2020-03-24 16:11 UTC
Hi @mikehardy,
thunderlink is a great addon and it is tightly integrated in my daily workflow. I wanted to tweak the output of the link, but the UI to do this seems to be broken on Ubuntu.

Here is a screenshot 
![Broken Thunderlink Preferences - Screenshot from 2020-03-24 16-58-43](https://user-images.githubusercontent.com/15739060/77448217-cac97380-6df0-11ea-9ab9-85a61258ec61.png)

It seems that [others got the same issue](https://github.com/mikehardy/thunderlink/issues/48#issuecomment-572928078).

The Error Console gives the following hint:
```
NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import] preferences.js:18
```
which points to the following [line](https://github.com/mikehardy/thunderlink/blob/2c10db1ea4b42d6943cf70eba5ac6ccaf38f3a1c/chrome/thunderlink/content/preferences.js#L18).
```javascript
Components.utils.import("resource:///modules/mailServices.js");
```
It seems that `mailServices.js` is not present on my system.
Did I miss a dependency? Where do I find the file?

I am using Thunderbird 68.5.0.

**Comment by mikehardy** [comment] 2020-03-24 16:25
As you mentioned, this is a duplicate of #48 so I'm going to close this
There is no such file anymore and a port of the add-on to 68 would recognize this
In the meantime I believe editing the preference file directly is possible and should work? Not ideal by any stretch, but daily workflows must not be blocked and that should get it done?

**Closed by mikehardy** 2020-03-24 16:25 UTC
