### ISSUE TITLE
ThunderBird 60+ Compatibility (clicking links, creating links works, pref setting does not)

### ISSUE THREAD

**Issue by gcamaril** [mikehardy/thunderlink#7] opened 2018-09-25 10:22 UTC
Thunderlink is currently not compatible with TB 60+ and the new extensions policy.

**Comment by avkhitry** [comment] 2018-10-11 11:09
Any chances this marvelous add on will rise from ashes?

**Comment by mikehardy** [comment] 2018-10-17 14:18
This feature will rise from the ashes! As a True Developer I was being lazy since getting access to the ability to fix it, and my personal Thunderbird installation had not updated to 60 (I use Ubuntu 18.04)

But guess what, in the system updates I received recently my Thunderbird just went to 60 so now my personal workflow is disrupted and I need to get this working. I'm not the most skilled javascript developer yet so it may take a few days but I'll get it.

**Comment by mikehardy** [comment] 2018-11-09 05:50
Today I became fully fed up with my broken workflow since the Ubuntu Thunderbird upgrade, and rolled up the sleeves. I have thunderlinks working in the sense you can create them and use them again.

You have indicated by participating here that you are interested. I see no harm in trying this, so someone besides myself can provide feedback: https://github.com/mikehardy/thunderlink/releases/tag/1.2.2-beta2

Can you configure thunderlink via the preferenes? Hahahaha no. But that's next (and maybe very quickly). Because using the advanced config editor in normal usage is riduclous.

**Comment by mikehardy** [comment] 2018-11-12 16:55
I just double-checked and in my normal email profile on Thunderbird it is still correctly creating links and displaying messages. Anyone else trying this? Would love to know if 1.2.2-beta2 is working for others as I prepare to tackle preference saving

**Comment by mikehardy** [comment] 2018-11-12 18:46
Hi @avkhitry - thanks for trying! Believe it or not, I think that's a positive sign. Thunderbird actually loaded (previously it would not even load on TB60), and it attempted to handle the email (previously it couldn't do that even after loading).

I have also seen this message in my testing and what it indicated to me was that the mail message simply didn't exist for whatever reason. It was correct too. Are you completely sure the email with that message id exists?

As a second test (since you already have it installed) - could you try right-clicking in a message window, making a new thunderlink and then trying to use it? If that fails as well then it's definitely a thunderlink bug. If that works, then I strongly suspect that the message just isn't there ?

**Comment by avkhitry** [comment] 2018-11-12 20:03
Well, I create link from existing mail by using right-click->Thunderlink-> local cmd option, so I`m pretty sure that these mails are exist. I tried different mails. Was unable to test "pure thunderlink", without cmd options, because my attempts to register protocol still fruitless.

**Comment by avkhitry** [comment] 2018-11-12 20:15
Here goes interesting thing: links of type 
"/usr/lib/thunderbird/thunderbird" -thunderlink  thunderlink://messageid=SN6PR05MB4719DDA88716E8AFB9DD7662ECC10@SN6PR05MB4719.namprd05.prod.outlook.com
and 
"/usr/lib/thunderbird/thunderbird" -thunderlink  thunderlink://messageid=20181031140902.1.3F97408A12F2DE35@projecis.com
are working well - open Thunderbird and switch to target mail. No errors here!
But links of type 
"/usr/lib/thunderbird/thunderbird" -thunderlink  thunderlink://messageid=000901d46c9d$f87576e0$e96064a0$@ru and 
"/usr/lib/thunderbird/thunderbird" -thunderlink  thunderlink://messageid=00dc01d46c3f$afcf87e0$0f6e97a0$@synergycro.ru
are not working at all, returning "Couldn't find an email message for ThunderLink"
in one case it even opened wrong email - not that from thunderlink was created, but its "parent" (mail for which it was a reply):
"/usr/lib/thunderbird/thunderbird" -thunderlink  thunderlink://messageid=31512504-35c1-6175-58c8-0e665bfa5f48@synergycro.ru - opens my mail in "send", but was created from "inbox" mail.

**Comment by avkhitry** [comment] 2018-11-12 21:47
I`ve checked couple of working and non-working links, in all cases Message-ID within source of email is identical to generated thunderlink, so, probably, its not link generation

**Comment by mikehardy** [comment] 2018-11-12 21:58
great, that helps, I'll try to poke the current code with some unit tests and the message ids that were failing to see what I can see.

**Comment by jqueipoll** [comment] 2018-11-13 08:36
Its working for me. Even the old links work. I open the links from 
org-mode buffers in emacs (I create TODOs and link the corresponding 
mail to them)

By the way, thank you for your work. It's very useful for me.


Juan Queipo de Llano Moya

**Comment by mikehardy** [comment] 2018-11-13 11:12
@tekvsadan I'm not sure what you mean by Thunderbird already open, that is my main usage and it works for me? Can you open an issue with exact steps to reproduce what you get vs what you expect? Bonus points for a screen cast video link to YouTube to make sure I understand

And to all - thanks for checking it and reporting! You're welcome for the work, and maybe together we can make this wonderful little add on work really well again

**Comment by mobileartur** [comment] 2018-11-13 12:21
I can report that 1.2.2.2 beta 2 **works OK** on my Windows 10 1803 17134.376 with Thunderbird 60.3.0 32bit. I created new links and checked also old ones. Everything works so far. I have the old registry mod and didn't; change anything 0 just installed the new Thunderlink beta.

BTW: Thank you for this great add-on. I created my GitHub account because of this project! LOL! THX!

**Comment by mikehardy** [comment] 2018-11-13 12:33
@mobileartur - thanks for the report, glad the basic use cases are working for you, that was my goal though it hasn't worked for everyone yet :-)

> BTW: Thank you for this great add-on. I created my GitHub account because of this project! LOL! THX!

Master hacker status in your future, get to it! :-). Cheers

**Comment by tekvsakdan** [comment] 2018-11-13 13:36
Let me explain again what bothers me. If Thunderbird is already open and if I click on thunderlink:// in a browser, it finds a message in a Thunderbird, but it doesn't open the message in a new tab. When Thunderbird is closed and if we click on thunderlink://, the Thunderbird opens only the message. The same command but 2 different results which depends if the Thunderbird is closed or open. Maybe I didn't correctly set the .desktop file or mimetype.

**Comment by mikehardy** [comment] 2018-11-13 13:47
@tekvsakdan - ah I see. Thunderlink has different modes of operation - new tab, new message etc, set in the preferences. Perhaps whatever mode you have configured, in your installation, isn't functioning correctly? 

For reference, I have the "preference name", `extensions.thunderlink.open-tl-behaviour` set to string type, value `openInNewWindow` and it works for me.

What's your setting? If you change it to openInNewWindow, does that improve things? If we can track this down, I can fix it as well

Thanks for the extra info

**Comment by tekvsakdan** [comment] 2018-11-13 14:10
I have change `extensions.thunderlink.open-tl-behaviour` to `openInNewTab` and it works as expected.

**Comment by mikehardy** [comment] 2018-11-13 14:16
@tekvsakdan very happy to hear you are working now, but what was the prior value? Because it sounds like there is an error in handling whatever it was before and it would be good to know + fix it. Cheers

**Comment by tekvsakdan** [comment] 2018-11-13 14:19
@mikehardy the prior value was `bySelect` or something. It is the default value.

**Comment by mikehardy** [comment] 2018-11-13 14:19
Excellent - an error in handling the default value :man_facepalming: :-). Thanks again for the testing and the report.

**Comment by Olifair** [comment] 2018-11-13 15:31
I would like to test, too. Thanks a lot mikehardy that you have been taking this up. 
mobileartur : how have you registered the protocol on windows 10 ? I have just switched to a new computer from windows 7 to 10  (as well as switching to the Thundrbird 60 with all the problems with most of the plugins I use ) and am not yet very firm on how to do things with windows 10. Thanks in advance for any tips you can give me.

**Comment by mikehardy** [comment] 2018-11-13 15:41
@Olifair @mobileartur if there are any changes needed to the README.md file with respect to window please let me know (or propose a PR, or make a wiki page? anything works for me) - I am on Ubuntu and Mac so I won't be able to help people with new windows instructions unfortunately

**Comment by mobileartur** [comment] 2018-11-13 19:11
> mobileartur : how have you registered the protocol on windows 10 ? I have just switched to a new computer from windows 7 to 10 (as well as switching to the Thundrbird 60 with all the problems with most of the plugins I use ) and am not yet very firm on how to do things with windows 10.

I use the same .reg file as for Windows 7 64 bit:

```
REGEDIT4
[HKEY_CLASSES_ROOT\thunderlink]
@="URL:thunderlink Protocol"
"URL Protocol"=""
[HKEY_CLASSES_ROOT\thunderlink\shell]
[HKEY_CLASSES_ROOT\thunderlink\shell\open]
[HKEY_CLASSES_ROOT\thunderlink\shell\open\command]
@=""C:\\Program Files (x86)\\Mozilla Thunderbird\\thunderbird.exe" -thunderlink "%1""
```

> Create a file with .reg extension, copy the stuff between the dashes into it, changing the path to the thunderbird.exe if necessary, double-click on the file, confirm execution, done.

It works on Widows 10 64 bit with Thunderbird 32 bit. When you use Thunderbird 64 bit you have to change the path to "C:\\Program Files\\Mozilla Thunderbird\\thunderbird.exe", but 64 bit version is not recommended on Windows. It can have some issues with other plugins and add-ons.

I updated the README.md with this info.

**Comment by mikehardy** [comment] 2018-11-13 19:27
@mobileartur that's fantastic information and I'd love to have that added to / committed in the main repo but I don't see a pull request to alter it? I even looked in your local repo (where you'd make the change first before opening a pull request for me to merge in to the code here) and I didn't see a commit...

**Comment by mobileartur** [comment] 2018-11-13 19:35
I can see it under "Your branches patch-1 Updated 34 minutes ago by mobileartur ". I created a pull request. Hmmm.... As I said this is my first time on Github as a participant. :D

**Comment by mikehardy** [comment] 2018-11-13 19:41
Hmm - maybe github had a hiccup, anyway, I just saw it and merged it. First pull request? 🎊 🍾  :-)

**Comment by mobileartur** [comment] 2018-11-13 20:29
@mikehardy Yeah! 🍾

**Comment by Olifair** [comment] 2018-11-14 12:17
mobileartur I just tested the installation. Thunderlink installed Ok on my Thunderbird 60.3.0 32 bits on a windows 10 64 bit laptop. Then I put the proposed script with the registry values into a .reg and ran it. The registry values were created, except the '"command" one was empty and did not contain the
""C:\\Program Files (x86)\\Mozilla Thunderbird\\thunderbird.exe" -thunderlink "%1""
I have tried to put it manually, trying different versions with our without the """ but when I click on the created thunderlink, I get an error that no application is linked to this protocol. 
any ideas ?

**Comment by mikehardy** [comment] 2018-12-09 02:16
Fixed with #22 - there will be a new release shortly, hopefully officially through the add-ons site so people get updates

There are still problems as submitted here (thanks everyone!) but I've created new issues for each of them. I don't believe there are "Thunderbird 60 Compatibility" issues anymore

**Closed by mikehardy** 2018-12-09 02:16 UTC
Labels: Priority-High

**Comment by mikehardy** [comment] 2018-12-10 15:18
They new version (1.2.3) is live on the official servers. If you've installed a test build here, maybe you could upgrade and just receive updates without effort on your part going forward? https://addons.thunderbird.net/en-US/thunderbird/addon/thunderlink/

A huge thanks to everyone for the feedback here. Knowing there were a few other souls out there interested in this kept me motivated to finish it. Enjoy the new build and I wish everyone increased productivity in the future ;-)

**Comment by mikehardy** [comment] 2018-12-10 15:22
@simonthum - If I have found the correct person, you are the only other user I see on the Add-Ons stat board that appears to have a forked-but-working version of this add-on. You may be interested in going mainline again, joining the party here? Cheers

**Comment by simonthum** [comment] 2019-04-26 20:06
Hi Mike - thanks for your efforts! ATM I honestly have no idea what to do about TL however. I am a happy user ;)
